version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant
    pid: host
    volumes:
      - ./hass-config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    networks:
        rede_home_assistant:
            ipv4_address: 10.5.0.2        
    ports:
      - "8123:8123"
      - "443:443"
    depends_on:
      - mariadb
      - mosquitto
  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: ha_db
      MYSQL_USER: homeassistant
      MYSQL_PASSWORD: "${HA_MYSQL_PASSWORD}"
      PUID: "${PUID}"
      PGID: "${PGID}"
    volumes:
      - ./mariadb:/config
    ports:
      - "3306:3306"
    networks:
        rede_home_assistant:
            ipv4_address: 10.5.0.3      
  nodered:
    container_name: nodered
    image: nodered/node-red
    ports:
      - "1880:1880"
    networks:
        rede_home_assistant:
            ipv4_address: 10.5.0.4      
    volumes:
      - ./nodered:/data
    depends_on:
      - homeassistant
      - mosquitto
    environment:
      TZ: "America/Sao_Paulo"
    restart: unless-stopped
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "1884:1884"
    networks:
        rede_home_assistant:
            ipv4_address: 10.5.0.5      
    volumes:
      - "./mosquitto/config:/mosquitto/config"
      - "./mosquitto/data:/mosquitto/data"
      - "./mosquitto/log:/mosquitto/log"
    environment:
      - TZ=America/Sao_Paulo
    user: "${PUID}:${PGID}"
networks:
  rede_home_assistant: 
    driver: bridge   
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1