version: '3'
services:
  hassio:
    image: homeassistant/amd64-hassio-supervisor
    container_name: hassio_supervisor
    privileged: true
    entrypoint: ["/bin/bash", "-c", "/scripts/start_hassio.sh"]
    security_opt:
      - seccomp:unconfined
    environment:
      - HOMEASSISTANT_REPOSITORY=homeassistant/qemux86-64-homeassistant
      - SUPERVISOR_SHARE=${SUPERVISOR_SHARE}
      - SUPERVISOR_NAME=hassio_supervisor
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/var/run/dbus/system_bus_socket
    volumes:
      - ${SUPERVISOR_SHARE}:/data
      - ./scripts:/scripts
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket 
  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: homeassistant_db
      MYSQL_USER: user_db_homeassistant
      MYSQL_PASSWORD: "${HA_MYSQL_PASSWORD}"
      PUID: "${PUID}"
      PGID: "${PGID}"
    volumes:
      - ${DIRETORIO_CONFIG_MARIADB}:/config
    ports:
      - "3306:3306"
    networks:
        rede_docker:
            ipv4_address: 10.5.0.3        
  nodered:
    container_name: nodered
    image: nodered/node-red:latest
    ports:
      - "1880:1880" 
    networks:
        rede_docker:
            ipv4_address: 10.5.0.4        
    volumes:
      - ${DIRETORIO_DATA_NODERED}:/data
    depends_on:
      - mosquitto
    environment:
      TZ: "${ZONA_PAIS}"
    restart: unless-stopped
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "1884:1884"
    networks:
        rede_docker:
            ipv4_address: 10.5.0.5     
    volumes:
      - ${DIRETORIO_CONFIG_MOSQUITTO}:/mosquitto/config      
      - ${DIRETORIO_DATA_MOSQUITTO}:/mosquitto/data
      - ${DIRETORIO_LOG_MOSQUITTO}:/mosquitto/log
networks:
  rede_docker: 
    driver: bridge   
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1      