version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant
    volumes:
      - ./homeassistant/config
      - ./etc/localtime:/etc/localtime:ro
    restart: unless-stopped 
    network_mode: host
    depends_on:
      - mariadb
      - mosquitto
  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: ha_db
      MYSQL_USER: homeassistant
      MYSQL_PASSWORD: "${HA_MYSQL_PASSWORD}"
      PUID: "${PUID}"
      PGID: "${PGID}"
    volumes:
      - ./mariadb/config:/config
    ports:
      - "3306:3306"
    networks:
        rede_docker:
            ipv4_address: 10.5.0.3        
  nodered:
    container_name: nodered
    image: nodered/node-red:latest
    ports:
      - "1880:1880" 
    networks:
        rede_docker:
            ipv4_address: 10.5.0.4        
    volumes:
      - ./nodered/data:/data
    depends_on:
      - homeassistant
      - mosquitto
    environment:
      TZ: "America/Sao_Paulo"
    restart: unless-stopped
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "1884:1884"
    networks:
        rede_docker:
            ipv4_address: 10.5.0.5     
    volumes:
      - "./mosquitto/config:/mosquitto/config"      
      - "./mosquitto/data:/mosquitto/data"
      - "./mosquitto/log:/mosquitto/log"
networks:
  rede_docker: 
    driver: bridge   
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1      