version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant
    volumes:
      - ${DIRETORIO_CONFIG_HOMEASSISTANT}:/config
      - ${DIRETORIO_CONFIG_TIME}:/etc/localtime:ro
      - ${DIRETORIO_CERTIFICADO_HOMEASSISTANT}:/tmp
    restart: unless-stopped 
    network_mode: host
    depends_on:
      - mariadb
      - mosquitto
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID="${PUID}"
      - PGID="${PGID}"
      - TZ="${ZONA_PAIS}"
      - URL="${URL_DUCKDNS}"
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${TOKEN_DUCKDNS}
      - EMAIL=${EMAIL_SWAG}
      - SUBDOMAINS=wildcard
    volumes:
      - ${DIRETORIO_CONFIG_SWAG}:/config 
      - ${DIRETORIO_CONFIG_TIME}:/etc/localtime:ro
    ports:
      - 80:80
    restart: unless-stopped      
  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: homeassistant_db
      MYSQL_USER: user_db_homeassistant
      MYSQL_PASSWORD: "${HA_MYSQL_PASSWORD}"
      PUID: "${PUID}"
      PGID: "${PGID}"
    volumes:
      - ${DIRETORIO_CONFIG_MARIADB}:/config
    ports:
      - "3306:3306"
    networks:
        rede_docker:
            ipv4_address: 10.5.0.3        
  nodered:
    container_name: nodered
    image: nodered/node-red:latest
    ports:
      - "1880:1880" 
    networks:
        rede_docker:
            ipv4_address: 10.5.0.4        
    volumes:
      - ${DIRETORIO_DATA_NODERED}:/data
    depends_on:
      - homeassistant
      - mosquitto
    environment:
      TZ: "${ZONA_PAIS}"
    restart: unless-stopped
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "1884:1884"
    networks:
        rede_docker:
            ipv4_address: 10.5.0.5     
    volumes:
      - ${DIRETORIO_CONFIG_MOSQUITTO}:/mosquitto/config      
      - ${DIRETORIO_DATA_MOSQUITTO}:/mosquitto/data
      - ${DIRETORIO_LOG_MOSQUITTO}:/mosquitto/log
networks:
  rede_docker: 
    driver: bridge   
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1      